### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "akhilesh1@gmail.com",
    "password": "akhilesh"
}

### signin user

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "akhilesh@gmail.com",
    "password": "akhilesh"
}

### Get the currently signin user

GET http://localhost:3000/auth/whoami

### Find a perticular user with a given ID

GET http://localhost:3000/auth/10

### Find all users with a given email

GET http://localhost:3000/auth?email=akhilesh123456@gmail.com


### Delete a user with given a id

DELETE  http://localhost:3000/auth/4

### Update a user

PATCH http://localhost:3000/auth/5
Content-Type: application/json

{
    "email":"akhi@gmail.com"
}
